default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tw-clone_development
test:
  <<: *default
  database: tw-clone_test
production:
  <<: *default
  database: tw-clone_production
  username: tw-clone
  password: <%= ENV['TW-CLONE_DATABASE_PASSWORD'] %>
